// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: soldier.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SoldierService_TakeDamage_FullMethodName = "/soldier.SoldierService/TakeDamage"
)

// SoldierServiceClient is the client API for SoldierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SoldierServiceClient interface {
	TakeDamage(ctx context.Context, in *DamageRequest, opts ...grpc.CallOption) (*DamageResponse, error)
}

type soldierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSoldierServiceClient(cc grpc.ClientConnInterface) SoldierServiceClient {
	return &soldierServiceClient{cc}
}

func (c *soldierServiceClient) TakeDamage(ctx context.Context, in *DamageRequest, opts ...grpc.CallOption) (*DamageResponse, error) {
	out := new(DamageResponse)
	err := c.cc.Invoke(ctx, SoldierService_TakeDamage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SoldierServiceServer is the server API for SoldierService service.
// All implementations must embed UnimplementedSoldierServiceServer
// for forward compatibility
type SoldierServiceServer interface {
	TakeDamage(context.Context, *DamageRequest) (*DamageResponse, error)
	mustEmbedUnimplementedSoldierServiceServer()
}

// UnimplementedSoldierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSoldierServiceServer struct {
}

func (UnimplementedSoldierServiceServer) TakeDamage(context.Context, *DamageRequest) (*DamageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeDamage not implemented")
}
func (UnimplementedSoldierServiceServer) mustEmbedUnimplementedSoldierServiceServer() {}

// UnsafeSoldierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SoldierServiceServer will
// result in compilation errors.
type UnsafeSoldierServiceServer interface {
	mustEmbedUnimplementedSoldierServiceServer()
}

func RegisterSoldierServiceServer(s grpc.ServiceRegistrar, srv SoldierServiceServer) {
	s.RegisterService(&SoldierService_ServiceDesc, srv)
}

func _SoldierService_TakeDamage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DamageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SoldierServiceServer).TakeDamage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SoldierService_TakeDamage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SoldierServiceServer).TakeDamage(ctx, req.(*DamageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SoldierService_ServiceDesc is the grpc.ServiceDesc for SoldierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SoldierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "soldier.SoldierService",
	HandlerType: (*SoldierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TakeDamage",
			Handler:    _SoldierService_TakeDamage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "soldier.proto",
}
