apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: game-manifests
  files:
  - ./blue-team-deployment.yaml
  - ./red-team-deployment.yaml

resources:
- ./game-master.yaml