apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-soldiers
spec:
  replicas: 20
  selector:
    matchLabels:
      app: soldier
      team: red
  template:
    metadata:
      labels:
        app: soldier
        team: red
    spec:
      containers:
      - name: soldier
        image: metooo/soldier:v1
        env:
        - name: SOLDIER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENEMY_SERVICE
          value: "blue-team:50051"
        - name: REDIS_ADDR
          value: "redis-service:6379"
        - name: TEAM
          value: red
        - name: HEALTH
          value: "150"
        - name: ATTACK_POWER
          value: "40"
        - name: PORT
          value: "50051"
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: red-team
spec:
  selector:
    app: soldier
    team: red
  ports:
    - port: 50051
      targetPort: 50051