apiVersion: v1
kind: Service
metadata:
  name: soldier-service
spec:
  selector:
    app: soldier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soldier-deployment
  labels:
    app: soldier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soldier
  template:
    metadata:
      labels:
        app: soldier
    spec:
      containers:
      - name: soldier
        image: metooo/soldier:v0
        ports:
        - containerPort: 8080
